def ksFile = rootProject.file('signing.properties')
def props = new Properties()
if (ksFile.canRead()) {
    props.load(new FileInputStream(ksFile))
    def keyFile = props['KEYSTORE_FILE'] ? rootProject.file(props['KEYSTORE_FILE']) : null

    if (keyFile != null && keyFile.exists() && keyFile.length() > 0 && props['KEYSTORE_ALIAS']) {
        android.signingConfigs.sign.storeFile keyFile
        android.signingConfigs.sign.storePassword props['KEYSTORE_PASSWORD']
        android.signingConfigs.sign.keyAlias props['KEYSTORE_ALIAS']
        android.signingConfigs.sign.keyPassword props['KEYSTORE_ALIAS_PASSWORD']
    } else {
        android.signingConfigs.sign.initWith(android.signingConfigs.debug)
    }
} else {
    android.signingConfigs.sign.initWith(android.signingConfigs.debug)
}
